### ISSUE TITLE
translate make problem with

### ISSUE THREAD

**Issue by aurlev** [varunsridharan/woocommerce-quick-buy#11]
while translate to an rtl lang (use wordpress setting) there almost have no option to edit product as downlowd or virtual. all that line is just moving some how to the other side of the line. triyng to fix it with update old version of wordpress  or turn off the other plugins did not fix it. 
it look to me as a woocommerce bug
l

**Comment by varunsridharan** [comment]
@aurlev 
Hi
I really cant understand the bug. could you please provide me more information with some screenshots too.

And if its a WooCommerce bug please post this into the woocommerce repo. not here .

Thanks

**Comment by aurlev** [comment]
hi technofreaky
hear is a screenshot. Thanks
  <img src=https://sites.google.com/site/yamiidigi/home/woo_screenshot.png>

**Comment by varunsridharan** [comment]
@aurlev This issue is not with our plugin :(

**Comment by aurlev** [comment]
technofreaky  , it happen only when use the wp translate (site lang as rtl). i know the woo conect it to be translated either. so it seems to me that the issue while woo contact to wp lang.

any way if you will do an idea to solve it will be Appreciated

other issue is on the review -even that  " Ratings are required to leave a review" is not sign. The  required remained. And there is not any way to rate with star only.

if it a woo or not issue - what ever you suggest will be grateful

**Comment by varunsridharan** [comment]
@aurlev 
i told that this is not the correct place report you need to report in WooCommerce .. not here. 

this repo is a plugin for woocommerce not woocommerce... understood ?

**Comment by aurlev** [comment]
wooo i'm sorry so much. your pluggin quik buy is great, Definitely !!

thank you so much !
