### ISSUE TITLE
Quick Buy button not working for Custom Product types

### ISSUE THREAD

**Issue by maneshmpp** [varunsridharan/woocommerce-quick-buy#13]
Quick Buy button not working for Custom Product types

**Comment by varunsridharan** [comment]
@Maneshmpp ? can you please explain what product type ?

**Comment by maneshmpp** [comment]
I have added a new product type called "books". Buy now button is working for Simple product but not for the new one. Below is my code which adds new product type.

**Comment by varunsridharan** [comment]
@Maneshmpp right now our plugin dose not support custom product types. :(
