### ISSUE TITLE
Adding htmlclass to shortcode renders incorrectly

### ISSUE THREAD

**Issue by brettshumaker** [varunsridharan/woocommerce-quick-buy#14]
When using the `htmlclass` attribute on the `[wc_buy_now_link]` shortcode, the value specified is appended to `$defined_class` without a preceding space. This renders that `htmlclass` value useless as it connects to the `quick_buy_'.$pid` class.

Submitting pull request.

**Comment by brettshumaker** [comment]
@technofreaky - just tagging you so you get a notification on this issue and pull request. 👍

**Comment by varunsridharan** [comment]
#15 Pull Request Merged :)
