### ISSUE TITLE
Simple Subscriptions with WooCommerce Not Working

### ISSUE THREAD

**Issue by BradleyDB** [varunsridharan/woocommerce-quick-buy#16]
As the title says. When the selected product is a simple subscription, there is no redirect. Other products seem to work fine.

**Comment by zenmedia** [comment]
I had a similar issue, and i updated https://github.com/varunsridharan/woocommerce-quick-buy/blob/master/includes/class-frontend.php#L145 with an array check and added the product types which i required.

**Comment by varunsridharan** [comment]
Fixed in upcoming version. and its working.
