### ISSUE TITLE
In shortcode class need space

### ISSUE THREAD

**Issue by fingerprintweb-person** [varunsridharan/woocommerce-quick-buy#18]
in shortcode htmlclass=" button" - is nesesery to add white char on begining

**Comment by varunsridharan** [comment]
@fingerprintweb can you please explain a bit on what exactly you are trying to say ?

**Comment by fingerprintweb-person** [comment]
in shortcode atts  htmlclass=" some-class next class" - is nesesery to add space "<space>some-class next class" beacouse in finale code custom classes is merge
