### ISSUE TITLE
Quick Buy With Quantity

### ISSUE THREAD

**Issue by ernestas-zekas** [varunsridharan/woocommerce-quick-buy#2]
When I set some product quantity and push “Quick buy” button it only adds to cart one product – not the quantity I set.

**Comment by varunsridharan** [comment]
:+1:  We have updated our plugin with the requested feature 

New Plugin Version 0.4
Plugin URL : http://wordpress.org/plugins/woocommerce-quick-buy/

**Comment by remcginn** [comment]
I am using ver 0.12.1 and it seems this issue has resurfaced.  I see in the PHP where the quantity value is set to 1.  But it will not pick up the number I adjust in the value field.
