### ISSUE TITLE
Quick Buy Shortcodes not working

### ISSUE THREAD

**Issue by monishrnath** [varunsridharan/woocommerce-quick-buy#26]
Woocommerce -> Settings -> Products -> Quick Buy is not available. 
The shortcodes are not working. The quick buy button is seen on the product pages and works.

WooCommerce version: 3.7.0
Quick Buy For WooCommerce version: 2.1
Wordpress Version: 5.2.3

Checked all other settings too, no luck. Please advise. 
![a1](https://user-images.githubusercontent.com/6657502/65513631-3772bc80-def9-11e9-97cc-da75aabf63a6.png)
![a2](https://user-images.githubusercontent.com/6657502/65513632-3772bc80-def9-11e9-8551-f4579cc13d45.png)
![a3](https://user-images.githubusercontent.com/6657502/65513633-3772bc80-def9-11e9-8e2f-f33246ef655e.png)

**Comment by varunsridharan** [comment]
@monishrnath which shortcode you are using ?

**Comment by monishrnath** [comment]
Quick buy link to create a tags. Actually the other one also not working.

**Comment by varunsridharan** [comment]
Hi There

I recently changed the shortcodes please refer https://wordpress.org/plugins/woocommerce-quick-buy/

Also provide the actual short code that you are using

1. `[wc_quick_buy]` will renders an actual click able button
2. `[wc_quick_buy_link]` will returns a actual URL (eg : https://example.com/quick-buy/11/3)

<blockquote><img src="https://ps.w.org/woocommerce-quick-buy/assets/banner-772x250.jpg?rev=2081945" width="48" align="right"><div>WordPress.org</div><div><strong><a href="https://wordpress.org/plugins/woocommerce-quick-buy/">Quick Buy For Woocommerce</a></strong></div><div>Add Quick buy button to redirect user to checkout / cart immediately when he click quick buy button</div></blockquote>
<blockquote><div><strong><a href="https://example.com/quick-buy/11/3">Example Domain</a></strong></div></blockquote>

**Comment by monishrnath** [comment]
https://example.com/quick-buy/11/3 , if I use this directly, I'm getting 404. 
Also I used the example on the readme while using the short code. 
Still no luck. 

Mainly, 
Woocommerce -> Settings -> Products -> Quick Buy is not available.

<blockquote><div><strong><a href="https://example.com/quick-buy/11/3">Example Domain</a></strong></div></blockquote>

**Comment by varunsridharan** [comment]
Well the new version has a lot of changes the settings page is now moved to

WooCommerce => Quick Buy

I kindly request you to check the wordpress.org  plugin's link : https://wordpress.org/plugins/woocommerce-quick-buy/

For updated screenshots & docs and also you need to update your permalinks once you modified your settings. so then only the url http://example.com/quick-buy/11/3 will work

also make sure that you change `{product_id}` into `{id}` in the url format field.

<blockquote><img src="https://ps.w.org/woocommerce-quick-buy/assets/banner-772x250.jpg?rev=2081945" width="48" align="right"><div>WordPress.org</div><div><strong><a href="https://wordpress.org/plugins/woocommerce-quick-buy/">Quick Buy For Woocommerce</a></strong></div><div>Add Quick buy button to redirect user to checkout / cart immediately when he click quick buy button</div></blockquote>
<blockquote><div><strong><a href="http://example.com/quick-buy/11/3">Example Domain</a></strong></div></blockquote>

**Comment by monishrnath** [comment]
Thank You so much for your quick response. Its working now.
 Please make sure to update this in the documentation. 
The {product_id} to {id} change in the settings and also the updation of Permalinks for it to work. 

Great Work, mate! L:ove the plugin.

**Comment by monishrnath** [comment]
Tried everything, product not adding to cart. Basket is empty. Was working briefly yesterday using link.
button Shortcodes not rendering. 
Updated to 2.2

**Comment by varunsridharan** [comment]
Hi 

I can't work on anything until you provide more information. the information which you shared does not help. i would like to have access to your website to check on the issue. so please send me the access. via my email id : varunsridharan23@gmail.com

**Comment by monishrnath** [comment]
I have sent the details. Please check.

**Comment by varunsridharan** [comment]
Issue fixed privately

**Comment by roccosgroi** [comment]
Hi, i have the same problem from few days on avada + woocommerce installation
