### ISSUE TITLE
Warning and no button using shortcode

### ISSUE THREAD

**Issue by silentFred** [varunsridharan/woocommerce-quick-buy#27]
**Describe the bug**
Warning shown when trying to use any shortcodes:
```
Warning: in_array() expects parameter 2 to be array, boolean given in 
public_html/wp-content/plugins/woocommerce-quick-buy/includes/shortcodes/class-button.php on line 50
```

**Comment by varunsridharan** [comment]
Hi There

Can you tell me if you have configured the settings for this plugin ?

**Comment by silentFred** [comment]
Yes i have configured most options

**Comment by rafwlaz** [comment]
@varunsridharan I found what is the problem with shortcode, in `class-link.php` there is an error with key which is getting options:
```php
$quick_buy_link_product_types = Helper::option( 'quick_buy_link_product_types', array( 'simple' ) );
```

should be:
```php
$quick_buy_link_product_types = Helper::option( 'enabled_product_types', array( 'simple' ) );
```

**Comment by varunsridharan** [comment]
hi there sorry about that. i will fix it in my next update

**Comment by stivenmart** [comment]
@varunsridharan Please update the base code plugin, i had the same problem of @rafwlaz their fix works perfectly.

**Comment by varunsridharan** [comment]
@stivenmart @rafwlaz thats not the proper fix. you need to update your settings page once after plugin is installed. please do check our settings page. we already have an **EXPERIMENTAL** feature for which we set the field's id as `quick_buy_link_product_types` which should not be changed.

**Comment by swalkergibson** [comment]
@varunsridharan The fix @rafwlaz found does appear to be the right one. If you leave the experimental feature unset, the `enabled_product_types` array will never be passed through to the link generator method.
