### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mdadmin1** [varunsridharan/woocommerce-quick-buy#28]
**Describe the bug**
i am trying place button on shop page like screenshot please check it There was an error

**Screenshots**
![Screenshot 2019-10-03 at 10 12 39 PM](https://user-images.githubusercontent.com/55654006/66146723-f67e5480-e62a-11e9-95cf-d99d74b1ecf4.png)

**Comment by varunsridharan** [comment]
Sorry about the delay please do update the plugin's settings.

**Comment by varunsridharan** [comment]
Fixed in latest version.
