### ISSUE TITLE
since last update, plugin is breaking my site if enabled

### ISSUE THREAD

**Issue by lucianahanan** [varunsridharan/woocommerce-quick-buy#29]
when i enable plugin, wp-admin is no longer acessible - only removing the plugin folder.

Fatal error: Class 'VSP\Base' not found in /home/ipstudio/public_html/www/wp-content/plugins/woocommerce-quick-buy/vendor/varunsridharan/vsp-framework/includes/class-framework-base.php on line 18

using wp last version, woocommerce last version.

**Comment by varunsridharan** [comment]
@YammYcoding sorry about the delayed response. :-( well i am trying to replicate the same issue here but i can't do you mind sharing FTP Access to debug the issue ? 
you can email me @ varunsridharan23@gmail.com
