### ISSUE TITLE
Shortcode not displaying on Pages / Posts in correct position

### ISSUE THREAD

**Issue by robertbobmattocks** [varunsridharan/woocommerce-quick-buy#3]
I understand this is more of a CSS issue as I have found the plugin to do as it is prescribed but the problem I am having is where the button wants to jump to the top of the page rather than sitting in the right spot where I am putting it in a container or div or table or inside another element . I tried several variations of this as well and got the same results . The button is working and functioning correctly . Just not going to the correct position .

I have to say that for the most part it is doing exactly what I want it to do but I'm guessing this may be a CSS class issue of some sort but when I add the shortcode anywhere else on my site its not going in other containers but putting itself below the title of the page. 

See the page I'm working on here on my site:

https://producedbydeuce.com/Multi-Media/printing-services/business-cards/

I'm using the Multi-purpose theme from 

ThemeMotive.com 

running the latest vers of the theme, woocommerce and wordpress 4.1

which is woocommerce ready and compatible. 

I'm trying to put the buttons in the table with the pricing on the page. I was going to generate several buttons linking to different products and try that. 

again the button itself is working great!

**Comment by varunsridharan** [comment]
Hi,

Bug Fixed And Released A New Version {WooCommerce Quick Buy V0.8}

**Comment by robertbobmattocks** [comment]
Excellent! I saw that and I was able to complete the rest of my buttons.
Thanks again!

I am seeing a duplicate TOS check boxc and paypal link on the checkout page
that it is redirecting to. I'm not sure If I did this in installing another
plugin or if this is another bug.

Please advise,

Robert Mattocks

On Sun, Feb 22, 2015 at 8:46 PM, Varun Sridharan notifications@github.com
wrote:

> Hi,
> 
> Bug Fixed And Released A New Version {WooCommerce Quick Buy V0.8}
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/technofreaky/woocomerce-quick-buy/issues/3#issuecomment-75479154
> .

## 

Robert Mattocks
Producer
Produced By Deuce
Cell: 386-299-0547
Office : 423-436-0333
Fax: 1-423-376-1201
www.producedbydeuce.com

_T-shirt & Apparel Screen Printing - Posters - Stickers - Signs - Web
Design / Web Marketing - CD / DVD Duplication and Packaging - Video
Production - Street Team Marketing - SEO & More! All under one
roof!Multi-Media Marketing & Printing Mad  Scientists!_

The information contained in this electronic transmission is legally
privileged and confidential information intended only for the use of the
individual or entity named above.  If the reader of this message is not the
intended recipient, you are hereby notified that any dissemination,
distribution, or copying of this electronic message is strictly prohibited.

**Comment by varunsridharan** [comment]
Hi,

We think that is might be a bug of our plugin. please allow us some time i will contact you directly via email
