### ISSUE TITLE
not working in 5.3.1

### ISSUE THREAD

**Issue by Taariqq** [varunsridharan/woocommerce-quick-buy#31]
**Describe the bug**
Plugin won't work in wp 5.3.1

**Comment by varunsridharan** [comment]
@Taariqq please explain on whats the exact issue ? We already tested it with latest WP & WC Version which works great. also make sure that  you have updated the settings and also test the same with the default theme provided by WordPress

**Comment by aichauhan** [comment]
@varunsridharan It's working perfectly on the homepage (Product grid), but not working on the single product page, when I click on the Quick buy button it just pushes the ADD TO CART button and nothing happens after that.
Here is my site's URL you can check yourself: https://www.salecity.pk/
I am running WP 5.3.2

<blockquote><div><strong><a href="https://www.salecity.pk/">SaleCity.pk – High End End Mobile Phone Accessories & Sport Gadgets | Smart Watches – High End End Mobile Phone Accessories & Sport Gadgets | Smart Watches</a></strong></div></blockquote>
