### ISSUE TITLE
Class 'VSP\Helper' not found error

### ISSUE THREAD

**Issue by novelview9** [varunsridharan/woocommerce-quick-buy#33]
recent version is not woring for me
```php
Fatal error: Uncaught Error: Class 'VSP\Helper' not found in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-quick-buy/includes/class-cart-clear-handler.php:33 Stack trace: #0 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(288): WC_Quick_Buy\Cart_Clear_Handler->validate_and_clear('') #1 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array) #2 /opt/bitnami/apps/wordpress/htdocs/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-quick-buy/includes/class-url-endpoint.php(66): do_action('wc_quick_buy_en...') #4 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(288): WC_Quick_Buy\URL_Endpoint->addtocart_if_quickbuy(Object(WP)) #5 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array) #6 /opt/bitnami/apps/wordpress/htdocs/wp-includes/plugin.php(544): WP_Hook->do_action(Array) #7 /opt/bitnami/apps/wordpres in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-quick-buy/includes/class-cart-clear-handler.php on line 33
```

**Comment by novelview9** [comment]
looking similar as this one https://github.com/varunsridharan/woocommerce-quick-buy/issues/29

**Comment by varunsridharan** [comment]
@novelview9 when did you get this error ?
for example while activating or when updating settings or when clicking quick buy button ?

**Comment by novelview9** [comment]
It shown up when I clicked my custom button(which has href "mysite.com/quick-order/7/1" )

I had have already product_id 7 item on my cart before I clicked it.

Actually, Im not good at php (*I'm python developer ), so I din't know how to solve that problem.
and I just changed only that line which occur error to comments and everything works fine.

**Comment by varunsridharan** [comment]
@novelview9 i am happy to help on this but i would like to know more. would like to share your site's url so i can try and get an idea about it ?

**Comment by novelview9** [comment]
Sure. its on developing now.
https://www.youwho.co/

<blockquote><img src="http://13.125.113.24/wp-content/themes/bridge/img/favicon.ico" width="48" align="right"><div><strong><a href="https://www.youwho.co/">YOUWHO | 나를 말해주는 또다른 언어,  YOUWHO</a></strong></div></blockquote>

**Comment by novelview9** [comment]
the static "구매하기" button use your library.
(now it only can show up with desktop device)

To use your function with only 1 item, 
I've added making empty cart function on custom action with your url request.
 
so My monkey patch to all about to put on function.php is on the right below.
(sadly, as I told you, Its my first time to write php code haha)  
```
add_action( 'init', 'woocommerce_clear_cart_url' );
function woocommerce_clear_cart_url() {
	if ( isset( $_GET['buy-now'] ) ) {
		global $woocommerce;
		$woocommerce->cart->empty_cart();
		exit( wp_redirect( home_url( '/quick-buy/17/1' ) ) );
	}
}
```

**Comment by varunsridharan** [comment]
@novelview9 when opening this url : https://www.youwho.co/?buy-now the plugin seems to be doing its work. where do you get this error ?

<blockquote><img src="http://13.125.113.24/wp-content/themes/bridge/img/favicon.ico" width="48" align="right"><div><strong><a href="https://www.youwho.co/?buy-now">Cart | YOUWHO</a></strong></div></blockquote>

**Comment by novelview9** [comment]
as I told you, I've customed your code 
```
'VSP\Helper' not found in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-quick-buy/includes/class-cart-clear-handler.php:33
```
Make that line unused.( with /* */)
I guess its the error about to load VSP\Helper module.

**Comment by varunsridharan** [comment]
@novelview9 so you are getting that error when using your custom code right ?

**Comment by novelview9** [comment]
Nope.
the error is occured by your code.

test your code with empty wordpress site.

class-cart-clear-handler.php
33line is not wokring properly
