### ISSUE TITLE
Add To Cart Button redirects to Checkout Page

### ISSUE THREAD

**Issue by josemigueli** [varunsridharan/woocommerce-quick-buy#36]
I have installed "Quick Buy For Woocommerce" in my store and since the last update the "Add to cart" button redirects to the checkout page. When I disable "Quick buy for Woocommerce" the "Add to cart" button works fine.

What should I do in this case? Is there a way to fix it or should I wait until the next update?

Thanks!

**Comment by mynamavi** [comment]
@varunsridharan  Nice plugin. But this bug need to be fixed. May you solve it fast

**Comment by varunsridharan** [comment]
@mynamavi @josemigueli thanks for reporting the issue.

I am currently working on a new version for @WPOnion which this base of this plugin. and it will be released in a day max. once its done i will fix and push an update for it.

**Comment by varunsridharan** [comment]
@mynamavi  @josemigueli  Fixed in recent update

**Comment by josemigueli** [comment]
The plugin works perfect now! Thank you!
