### ISSUE TITLE
Error when editing Shop Page

### ISSUE THREAD

**Issue by wooassist00** [varunsridharan/woocommerce-quick-buy#37]
Error when editing shop page - https://prnt.sc/tihdmd

Error codes from WordPress, please fix: 

WordPress version 5.4.2
Current theme: Storefront Child 01 (version 2.0.1)
Current plugin: Quick Buy For WooCommerce (version 2.7.3)
PHP version 7.3.18-1+ubuntu18.04.1+http://deb.sury.org/+1

Error Details
=============
An error of type E_ERROR was caused in line 150 of the file /wp-content/plugins/woocommerce-quick-buy/vendor/varunsridharan/vsp-framework/includes/core/traits/class-wc-helper.php. Error message: Uncaught Error: Call to a member function get_cart() on null in /wp-content/plugins/woocommerce-quick-buy/vendor/varunsridharan/vsp-framework/includes/core/traits/class-wc-helper.php:150
Stack trace:
#0 /wp-content/plugins/woocommerce-quick-buy/includes/class-button-generator.php(57): VSP\Helper::wc_has_product_in_cart(962)
#1 /wp-content/plugins/woocommerce-quick-buy/includes/class-button-placement.php(94): WC_Quick_Buy\Button_Generator->html()
#2 /wp-includes/class-wp-hook.php(287): WC_Quick_Buy\Button_Placement->shop_page_button('')
#3 /wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#4 /wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#5 /wp-content/plugins/woocommerce/templates/content-product.php(65): do_action('woocommerce_aft...')
#6 /wp-includes/templ

**Comment by varunsridharan** [comment]
@wooassist00 fixed in recent update.
