### ISSUE TITLE
A "1" appears where we place the shortcode

### ISSUE THREAD

**Issue by remcginn** [varunsridharan/woocommerce-quick-buy#6]
A "1" appears where we place the shortcode.  You can see it in the screenshot immediately above the "Buy Now" button.  The shortcode will place the button in that spot and at the top, but also adds this "1".
How do I get rid of this "1"?

![screenshot_quick_buy](https://cloud.githubusercontent.com/assets/13558791/8964327/d72ad370-35d9-11e5-9a07-24f360495929.png)

**Comment by varunsridharan** [comment]
issue solved in latest release
