### ISSUE TITLE
Quick Buy with Quantity

### ISSUE THREAD

**Issue by remcginn** [varunsridharan/woocommerce-quick-buy#7]
This was a closed issue (#2), and it seems this issue has resurfaced.  I am using ver 0.12.1, I see in the PHP where the quantity value is set to 1.  But it will not pick up the number I adjust in the quantity field.

Thank you for your help!

Ralph.

**Comment by varunsridharan** [comment]
Hi,

i checked in my local it perfectly works for me. can you please show me a demo. where the problem occurs
