### ISSUE TITLE
Add to Cart button cannot show when Quick Buy Plugin is activated 

### ISSUE THREAD

**Issue by acywu** [varunsridharan/woocommerce-quick-buy#8]
![image](https://cloud.githubusercontent.com/assets/7578682/10730147/225ed734-7c29-11e5-9f25-1a0197120aba.png)

**Comment by varunsridharan** [comment]
Hi,

Sorry for the dealy. :(
can you please tell me more info like

WordPress Version
WooCommerce Version
For Which product type its showing like. this
and if possible a live demo

**Comment by acywu** [comment]
This bug was fixed in the latest version, thanks!

**Comment by acywu** [comment]
This bug was fixed in the latest version, thanks!

Regards,
Wu Chun-yeung
Alex
