### ISSUE TITLE
Qty selection not available for Variable products

### ISSUE THREAD

**Issue by tushonline** [varunsridharan/woocommerce-quick-buy#9]
Hello, 
The plugin works fine on `simple` & `variable` products just fine. Thank you very much.

But, in case of `variable` products - the quantity selection is not available. The form does not display.

To confirm this: I removed `variable` products from plugin settings & kept enabled only for `simple` products -- then only I could see Qty box on variable product. 

Hope this helps. Thanks

**Comment by varunsridharan** [comment]
@tushonline 
I am very sorry i dint get any notification about this issue. :( 
i will sure check for the issue in my local and fix it :)
